spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    minimum-idle: 1
    maximum-pool-size: 10

